from __future__ import annotations

from datetime import UTC, datetime
import hashlib
import re

from imprint.adapters.protocol import ArtifactEnvelope
from imprint.schemas import Artifact, ArtifactClassification, ArtifactReference, ArtifactStoragePolicy


def sha256_text(value: str) -> str:
    digest = hashlib.sha256(value.encode("utf-8")).hexdigest()
    return f"sha256:{digest}"


def stable_identifier(prefix: str, *parts: str) -> str:
    token = hashlib.sha256("|".join(parts).encode("utf-8")).hexdigest()[:16]
    return f"{prefix}-{token}"


def opaque_source_id(source_type: str, source_id: str) -> str:
    return stable_identifier("source", source_type, source_id)


def derive_source_hints(envelope: ArtifactEnvelope) -> dict[str, object]:
    lowered = envelope.content.lower()
    stripped_lines = [line.strip() for line in envelope.content.splitlines() if line.strip()]
    lines = envelope.content.splitlines()
    paragraphs = [paragraph.strip() for paragraph in re.split(r"\n\s*\n", envelope.content) if paragraph.strip()]
    sentences = [segment.strip() for segment in re.split(r"[.!?]+", envelope.content) if segment.strip()]
    first_line = stripped_lines[0] if stripped_lines else ""
    first_sentence = sentences[0] if sentences else ""
    byte_count = len(envelope.content.encode("utf-8"))
    bullet_lines = [line for line in stripped_lines if re.match(r"^[-*]\s+", line)]
    heading_lines = [line for line in stripped_lines if line.startswith("#")]
    contrast_matches = re.findall(r"\bnot\b[^.!?\n]{0,80}\bbut\b", lowered)
    contractions = re.findall(r"\b\w+(?:'\w+)\b", envelope.content)
    causal_matches = re.findall(r"\b(because|therefore|thus|as a result|so that)\b", lowered)
    tradeoff_matches = re.findall(
        r"\b(tradeoff|trade-off|in exchange|at the cost of|instead of|rather than|versus| vs\.? )\b",
        lowered,
    )
    hedge_matches = re.findall(r"\b(maybe|perhaps|might|could|likely|possibly|seems?)\b", lowered)
    caveat_matches = re.findall(r"\b(however|although|though|depends|except|unless|while)\b", lowered)
    sequence_matches = re.findall(r"\b(first|second|third|then|next|finally)\b", lowered)
    before_after_matches = re.findall(r"\b(before|after)\b", lowered)
    example_matches = re.findall(r"\b(for example|for instance)\b", lowered)
    hints: dict[str, object] = {
        "line_count": len(envelope.content.splitlines()),
        "word_count": len(envelope.content.split()),
        "byte_count": byte_count,
        "oversized_artifact": byte_count > 10 * 1024 * 1024,
        "paragraph_count": len(paragraphs),
        "sentence_count": len(sentences),
        "bullet_line_count": len(bullet_lines),
        "heading_count": len(heading_lines),
        "contrast_marker_count": len(contrast_matches),
        "contraction_count": len(contractions),
        "causal_marker_count": len(causal_matches),
        "tradeoff_marker_count": len(tradeoff_matches),
        "hedge_marker_count": len(hedge_matches),
        "caveat_marker_count": len(caveat_matches),
        "sequence_marker_count": len(sequence_matches),
        "before_after_marker_count": len(before_after_matches),
        "example_marker_count": len(example_matches),
        "question_count": envelope.content.count("?"),
        "exclamation_count": envelope.content.count("!"),
        "first_line_word_count": len(first_line.split()),
        "first_sentence_word_count": len(first_sentence.split()),
        "short_paragraph_count": sum(1 for paragraph in paragraphs if len(paragraph.split()) <= 24),
        "contains_quote_marker": any(line.startswith(">") for line in stripped_lines),
        "contains_reply_header": "wrote:" in lowered,
        "contains_forward_marker": any(
            marker in lowered for marker in ("forwarded message", "begin forwarded message")
        ),
        "contains_notification_marker": any(
            marker in lowered
            for marker in ("unsubscribe", "notification", "do not reply", "noreply", "no-reply")
        ),
        "contains_template_marker": any(marker in envelope.content for marker in ("{{", "}}", "[[", "]]", "<<", ">>")),
        "contains_assistant_marker": any(
            marker in lowered for marker in ("assistant:", "generated by assistant", "ai assistant")
        ),
        "has_direct_opening": 0 < len(first_sentence.split()) <= 8,
        "uses_bullets": len(bullet_lines) > 0,
        "uses_headings": len(heading_lines) > 0,
        "uses_contrast_framing": len(contrast_matches) > 0,
        "uses_causal_explanation": len(causal_matches) > 0,
        "uses_tradeoff_framing": len(tradeoff_matches) > 0,
        "uses_hedging": len(hedge_matches) > 0,
        "uses_caveat_markers": len(caveat_matches) > 0,
        "uses_sequence_markers": len(sequence_matches) > 0,
        "uses_before_after_transition": len(before_after_matches) >= 2,
        "uses_example_marker": len(example_matches) > 0,
        "has_question_burst": envelope.content.count("?") >= 2,
        "has_exclamation_burst": envelope.content.count("!") >= 2 or "?!" in envelope.content,
    }
    return hints


def utc_datetime(value: datetime) -> datetime:
    if value.tzinfo is None:
        return value.replace(tzinfo=UTC)
    return value.astimezone(UTC)


def parse_timestamp(value: object) -> datetime | None:
    if value is None:
        return None
    if isinstance(value, datetime):
        return utc_datetime(value)
    if isinstance(value, (int, float)):
        return datetime.fromtimestamp(value, tz=UTC)
    if isinstance(value, str):
        normalized = value.strip()
        if normalized.endswith("Z"):
            normalized = normalized[:-1] + "+00:00"
        return utc_datetime(datetime.fromisoformat(normalized))
    raise ValueError(f"unsupported timestamp type: {type(value).__name__}")


def envelope_to_artifact(
    envelope: ArtifactEnvelope,
    *,
    storage_policy: ArtifactStoragePolicy,
) -> Artifact:
    content_hash = sha256_text(envelope.content)
    source_id = opaque_source_id(envelope.source_type, envelope.source_id)
    artifact_id = envelope.artifact_id_hint or stable_identifier(
        "artifact",
        envelope.source_type,
        envelope.source_id,
        content_hash,
    )
    classification_id = stable_identifier("classification", artifact_id, source_id)
    timestamp = utc_datetime(envelope.timestamp) if envelope.timestamp else None

    reference = ArtifactReference(
        artifact_id=artifact_id,
        source_id=source_id,
        artifact_type=envelope.artifact_type,
        source_type=envelope.source_type,
        content_hash=content_hash,
        timestamp=timestamp,
        time_bucket=envelope.time_bucket,
        raw_content_available=storage_policy.raw_content_available,
    )
    classification = ArtifactClassification(
        classification_id=classification_id,
        label=envelope.classification_label,
        authorship_origin=envelope.authorship_origin,
        authorship_confidence=envelope.authorship_confidence,
        reason_categories=[envelope.authorship_origin],
    )
    return Artifact(
        artifact_id=artifact_id,
        reference=reference,
        storage_policy=storage_policy,
        classification=classification,
        source_hints={**derive_source_hints(envelope), **envelope.metadata},
    )
