from __future__ import annotations

from datetime import UTC, datetime
import hashlib

from imprint.adapters.protocol import ArtifactEnvelope
from imprint.schemas import Artifact, ArtifactClassification, ArtifactReference, ArtifactStoragePolicy


def sha256_text(value: str) -> str:
    digest = hashlib.sha256(value.encode("utf-8")).hexdigest()
    return f"sha256:{digest}"


def stable_identifier(prefix: str, *parts: str) -> str:
    token = hashlib.sha256("|".join(parts).encode("utf-8")).hexdigest()[:16]
    return f"{prefix}-{token}"


def opaque_source_id(source_type: str, source_id: str) -> str:
    return stable_identifier("source", source_type, source_id)


def derive_source_hints(envelope: ArtifactEnvelope) -> dict[str, object]:
    lowered = envelope.content.lower()
    stripped_lines = [line.strip() for line in envelope.content.splitlines() if line.strip()]
    byte_count = len(envelope.content.encode("utf-8"))
    hints: dict[str, object] = {
        "line_count": len(envelope.content.splitlines()),
        "word_count": len(envelope.content.split()),
        "byte_count": byte_count,
        "oversized_artifact": byte_count > 10 * 1024 * 1024,
        "contains_quote_marker": any(line.startswith(">") for line in stripped_lines),
        "contains_reply_header": "wrote:" in lowered,
        "contains_forward_marker": any(
            marker in lowered for marker in ("forwarded message", "begin forwarded message")
        ),
        "contains_notification_marker": any(
            marker in lowered
            for marker in ("unsubscribe", "notification", "do not reply", "noreply", "no-reply")
        ),
        "contains_template_marker": any(marker in envelope.content for marker in ("{{", "}}", "[[", "]]", "<<", ">>")),
        "contains_assistant_marker": any(
            marker in lowered for marker in ("assistant:", "generated by assistant", "ai assistant")
        ),
    }
    return hints


def utc_datetime(value: datetime) -> datetime:
    if value.tzinfo is None:
        return value.replace(tzinfo=UTC)
    return value.astimezone(UTC)


def parse_timestamp(value: object) -> datetime | None:
    if value is None:
        return None
    if isinstance(value, datetime):
        return utc_datetime(value)
    if isinstance(value, (int, float)):
        return datetime.fromtimestamp(value, tz=UTC)
    if isinstance(value, str):
        normalized = value.strip()
        if normalized.endswith("Z"):
            normalized = normalized[:-1] + "+00:00"
        return utc_datetime(datetime.fromisoformat(normalized))
    raise ValueError(f"unsupported timestamp type: {type(value).__name__}")


def envelope_to_artifact(
    envelope: ArtifactEnvelope,
    *,
    storage_policy: ArtifactStoragePolicy,
) -> Artifact:
    content_hash = sha256_text(envelope.content)
    source_id = opaque_source_id(envelope.source_type, envelope.source_id)
    artifact_id = envelope.artifact_id_hint or stable_identifier(
        "artifact",
        envelope.source_type,
        envelope.source_id,
        content_hash,
    )
    classification_id = stable_identifier("classification", artifact_id, source_id)
    timestamp = utc_datetime(envelope.timestamp) if envelope.timestamp else None

    reference = ArtifactReference(
        artifact_id=artifact_id,
        source_id=source_id,
        artifact_type=envelope.artifact_type,
        source_type=envelope.source_type,
        content_hash=content_hash,
        timestamp=timestamp,
        time_bucket=envelope.time_bucket,
        raw_content_available=storage_policy.raw_content_available,
    )
    classification = ArtifactClassification(
        classification_id=classification_id,
        label=envelope.classification_label,
        authorship_origin=envelope.authorship_origin,
        authorship_confidence=envelope.authorship_confidence,
        reason_categories=[envelope.authorship_origin],
    )
    return Artifact(
        artifact_id=artifact_id,
        reference=reference,
        storage_policy=storage_policy,
        classification=classification,
        source_hints={**derive_source_hints(envelope), **envelope.metadata},
    )
